In [28]:
#IMPORTANDO BIBLIOTECAS
import pandas as pd
import numpy as np
import statistics as sts
import math as ma #from math import ceil #amostra Sistematica
from scipy import stats
#IMPORTANDO BIBLIOTECAS  - APRENDIZADO DE MÁQUINA
from sklearn.model_selection import train_test_split

#IMPORTANDO BIBLIOTECAS GRAFICAS
#import plotly.express as px
#import plotly.figure_factory as ff
#import seaborn as srn

In [4]:
dfInfert = pd.read_csv("./BaseDeDados/infert.csv")
dfInfert.shape

(248, 9)

In [5]:
dfInfert

,Unnamed: 0,education,age,parity,induced,case,spontaneous,stratum,pooled.stratum
0,1,0-5yrs,26,6,1,1,2,1,3
1,2,0-5yrs,42,1,1,1,0,2,1
2,3,0-5yrs,39,6,2,1,0,3,4
3,4,0-5yrs,34,4,2,1,0,4,2
4,5,6-11yrs,35,3,1,1,1,5,32
...,...,...,...,...,...,...,...,...,...
243,244,12+ yrs,31,1,0,0,1,79,45
244,245,12+ yrs,34,1,0,0,0,80,47
245,246,12+ yrs,35,2,2,0,0,81,54
246,247,12+ yrs,29,1,0,0,1,82,43
247,248,12+ yrs,23,1,0,0,1,83,40

In [8]:
x, _, y, _ = train_test_split(dfInfert.iloc[:, 2:9], # A amostra sera extraida das colunas de 2 a 9
                               dfInfert.iloc[:,1], #Identifica a coluna da extratificaçao
                               test_size= 0.5,
                               stratify= dfInfert.iloc[:,1]
                               )